### ISSUE TITLE
Pestañas, iconos en bootstrap y paleta de colores

### ISSUE THREAD

**Issue by fiorellasaro** [fiorellasaro/lim-2018-05-bc-core-am-socialnetwork#1]
He estado tratando de hacer las pestañas en bootstrap y no sale. Por otro lado, también he tenido dificultades con los iconos de google y facebook, utilizo las clases que le corresponden pero no se visualiza en el html.

Para hacer el diseño final creo que tenemos que definir colores. Jessica ha hecho un primer prototipo de alta fidelidad; sin embargo, por falta de tiempo creo que nos falto definir los colores y tipografia.

**Comment by BellaAguirre** [comment]
@fiorellasaro  Si estas usando bootstrap 4.1, pues leí que ya no trae los iconos osea hay que jalar otro link de iconos como  este que es el que recomienda el mismo bootstrap ;)  
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

**Comment by BellaAguirre** [comment]
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

**Comment by BellaAguirre** [comment]
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
`
